- name: set timezone to Moscow
  timezone:
    name: Europe/Moscow

- name: resolve hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      192.168.0.1 master
      192.168.0.2 node1
      192.168.0.3 node2

- name: Disable SWAP
  shell:
    cmd: |
      swapoff -a
  args:
    executable: /bin/bash

- name: Remove Swap from fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: disable firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: disable selinux
  ansible.posix.selinux:
    state: disabled

- name: ensure SELinux is set to disable mode
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

# настройка локального репозитория, если переменная с его адресом существует
- name: setup local repo
  block:

    - name: copy local repo file
      template:
        src: local.repo
        dest: /etc/yum.repos.d/local.repo
        owner: root
        group: root
        mode: '0644'

    - name: add local repo address
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: '{{ local_repo }} repo.local'

    - name: Install base tools
      ansible.builtin.dnf:
        name:
        - glibc-langpack-ru
        - vim
        - tcpdump
        - wget
        disablerepo: appstream,baseos,extras
        enablerepo: local
        disable_gpg_check: true
        update_cache: yes
        install_weak_deps: false

    - name: setup nodes
      block:
        - name: Install docker
          ansible.builtin.dnf:
            name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            disablerepo: appstream,baseos,extras
            enablerepo: local
            disable_gpg_check: true
            update_cache: yes
            install_weak_deps: false
        - name: start and enable docker service
          service: 
              name: docker
              state: started
              enabled: true

        - name: copy daemon.json
          template: 
            src: daemon.json
            dest: /etc/docker/daemon.json
            owner: root
            group: root
            mode: 0644

        - name: reload systemd
          command: systemctl daemon-reload

        - name: start and enable docker service
          service: 
              name: docker
              state: restarted
              enabled: true

        - name: Extract cri-dockerd
          ansible.builtin.unarchive:
            src: cri-dockerd-0.3.4.amd64.tgz
            dest: /home/vagrant/
            owner: vagrant
            group: vagrant

        - name: Copy the binary file cri-dockerd
          copy:
            src: /home/vagrant/cri-dockerd/cri-dockerd
            dest: /usr/local/bin
            owner: root
            group: root
            mode: 0755
            remote_src: yes

        - name: copy daemon.json
          template: 
            src: daemon.json
            dest: /etc/docker/daemon.json
            owner: root
            group: root
            mode: 0644

        - name: copy service and socket
          template: 
            src: "{{ item }}"
            dest: /etc/systemd/system/
            owner: root
            group: root
            mode: 0644
          with_items:
            - cri-docker.service
            - cri-docker.socket

        - name: reload systemd
          command: systemctl daemon-reload

        - name: start and enable cri-docker service
          service: 
              name: cri-docker
              state: restarted
              enabled: true

        

      when: "'node' in inventory_hostname"

  when: local_repo is defined

